-- AlterTable
ALTER TABLE "User" ADD COLUMN "bio" TEXT;
ALTER TABLE "User" ADD COLUMN "interests" TEXT;
ALTER TABLE "User" ADD COLUMN "links" TEXT;
ALTER TABLE "User" ADD COLUMN "profileImg" TEXT;
ALTER TABLE "User" ADD COLUMN "status" TEXT;
